# Generated by Django 6.0.4 on 2026-04-26 08:27

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='color',
            field=models.CharField(default='#2c3e50', help_text='CSS-цвет, например #3498db', max_length=20, verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.author_photo_upload_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.cover_upload_path, verbose_name='Обложка'),
        ),
    ]
