# Generated by Django 6.0.4 on 2026-04-26 13:30

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_genre_color_alter_author_photo_alter_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buylink',
            options={'ordering': ['id'], 'verbose_name': 'Ссылка на покупку', 'verbose_name_plural': 'Ссылки на покупку'},
        ),
        migrations.AddField(
            model_name='buylink',
            name='color',
            field=models.CharField(default='#FF6B35', help_text='CSS-цвет, например: #005bff или #1b5e20', max_length=20, verbose_name='Цвет кнопки'),
        ),
        migrations.AddField(
            model_name='buylink',
            name='icon',
            field=models.CharField(blank=True, choices=[('', 'Без иконки'), ('cart', '🛒 Корзина'), ('book', '📖 Книга'), ('link', '🔗 Ссылка'), ('star', '⭐ Звезда'), ('store', '🏪 Магазин')], default='', help_text='Необязательно — отображается перед названием', max_length=20, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, help_text='Картинка-фон для плашки жанра (рекомендуется 800×400 px)', null=True, upload_to=catalog.models.genre_image_upload_path, verbose_name='Фоновая картинка'),
        ),
        migrations.AlterField(
            model_name='buylink',
            name='store',
            field=models.CharField(help_text='Например: Литрес, Ozon, Яндекс Книги', max_length=100, verbose_name='Название магазина / кнопки'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='color',
            field=models.CharField(default='#2c3e50', help_text='Используется если нет картинки. Например: #3498db', max_length=20, verbose_name='Цвет фона (резерв)'),
        ),
    ]
