# Generated by Django 6.0.4 on 2026-04-28 11:42

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_buylink_options_buylink_color_buylink_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buylink',
            name='color',
            field=models.CharField(default='#FF6B35', help_text='HEX-цвет, например #005bff', max_length=20, verbose_name='Цвет кнопки'),
        ),
        migrations.AlterField(
            model_name='buylink',
            name='icon',
            field=models.FileField(blank=True, help_text='Необязательно. SVG или PNG, ~24×24 px', null=True, upload_to=catalog.models.store_icon_upload_path, verbose_name='Иконка (SVG/PNG)'),
        ),
        migrations.AlterField(
            model_name='buylink',
            name='store',
            field=models.CharField(help_text='Например: Литрес, Ozon, Яндекс Книги', max_length=100, verbose_name='Название кнопки'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='color',
            field=models.CharField(default='#2c3e50', help_text='CSS-цвет если нет картинки', max_length=20, verbose_name='Цвет фона (запасной)'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендуется 1200×400 px', null=True, upload_to=catalog.models.genre_image_upload_path, verbose_name='Фоновая картинка'),
        ),
    ]
